/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { IndicatorDefinition, CityData, SmartProject } from "./types";

export const CATEGORIES = [
  "Smart Governance",
  "Smart Mobility",
  "Smart Environment",
  "Smart Economy",
  "Smart Living",
  "Smart People",
] as const;

export const CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string; accent: string }> = {
  "Smart Governance": {
    bg: "bg-cyan-950/20",
    text: "text-cyan-400",
    border: "border-cyan-500/30",
    accent: "bg-cyan-500",
  },
  "Smart Mobility": {
    bg: "bg-amber-950/20",
    text: "text-amber-400",
    border: "border-amber-500/30",
    accent: "bg-amber-500",
  },
  "Smart Environment": {
    bg: "bg-emerald-950/20",
    text: "text-emerald-400",
    border: "border-emerald-500/30",
    accent: "bg-emerald-500",
  },
  "Smart Economy": {
    bg: "bg-purple-950/20",
    text: "text-purple-400",
    border: "border-purple-500/30",
    accent: "bg-purple-500",
  },
  "Smart Living": {
    bg: "bg-red-950/20",
    text: "text-red-400",
    border: "border-red-500/30",
    accent: "bg-red-500",
  },
  "Smart People": {
    bg: "bg-pink-950/20",
    text: "text-pink-400",
    border: "border-pink-500/30",
    accent: "bg-pink-500",
  },
};

export const INDICATOR_DEFINITIONS: IndicatorDefinition[] = [
  // Smart Governance
  {
    id: "gov-online-services",
    category: "Smart Governance",
    nameMs: "Penyediaan Perkhidmatan Atas Talian",
    nameEn: "Online Public Services Delivery",
    descriptionMs: "Peratusan perkhidmatan majlis tempatan yang boleh diselesaikan sepenuhnya atas talian oleh rakyat.",
    descriptionEn: "Percentage of local municipal services fully complete online by citizens.",
  },
  {
    id: "gov-open-data",
    category: "Smart Governance",
    nameMs: "Portal Data Terbuka Bandar",
    nameEn: "City Open Data Portal",
    descriptionMs: "Adanya portal perkongsian data terbuka yang menyediakan set data awam yang dikemas kini.",
    descriptionEn: "Existence of an updated open data sharing portal providing public datasets.",
  },
  {
    id: "gov-e-payment",
    category: "Smart Governance",
    nameMs: "Kutipan Hasil Secara Elektronik",
    nameEn: "Electronic Revenue Collection (e-Payment)",
    descriptionMs: "Semua pembayaran cukai pintu, saman, dan pajakan disokong melalui bayaran digital bersepadu.",
    descriptionEn: "All assessment tax, fines, and rental payments supported via integrated digital payment channels.",
  },
  {
    id: "gov-wifi",
    category: "Smart Governance",
    nameMs: "Infrastruktur Wi-Fi Awam Percuma",
    nameEn: "Free Public Wi-Fi Infrastructure",
    descriptionMs: "Zon Wi-Fi kelajuan tinggi percuma di semua bangunan awam utama dan dewan komuniti.",
    descriptionEn: "Free high-speed Wi-Fi zones in all major public administrative buildings and community halls.",
  },
  {
    id: "gov-citizen-engagement",
    category: "Smart Governance",
    nameMs: "Platform Maklum Balas Rakyat Digital",
    nameEn: "Digital Public Consultation Platform",
    descriptionMs: "Platform digital untuk kaji selidik awam, penyertaan bajet, dan perancangan dasar bandar.",
    descriptionEn: "Digital platform for public surveys, participatory budgeting, and urban policy planning.",
  },

  // Smart Mobility
  {
    id: "mob-traffic-mgmt",
    category: "Smart Mobility",
    nameMs: "Sistem Pengurusan Trafik Pintar (ITMS)",
    nameEn: "Intelligent Traffic Management System (ITMS)",
    descriptionMs: "Persimpangan lampu isyarat dilengkapi sensor AI untuk mengurangkan kesesakan secara dinamik.",
    descriptionEn: "Traffic light intersections equipped with AI sensors to dynamically reduce congestion.",
  },
  {
    id: "mob-realtime-transit",
    category: "Smart Mobility",
    nameMs: "Penjejakan Pengangkutan Awam Masa Nyata",
    nameEn: "Real-Time Public Transit Tracking",
    descriptionMs: "Aplikasi mudah alih rasmi yang memaparkan kedudukan tepat masa sebenar bagi bas dan tren bandar.",
    descriptionEn: "Official mobile application displaying live locations and ETA for city buses and trains.",
  },
  {
    id: "mob-ev-infra",
    category: "Smart Mobility",
    nameMs: "Rangkaian Stesen Pengecasan Kenderaan Elektrik",
    nameEn: "Electric Vehicle (EV) Charging Infrastructure",
    descriptionMs: "Stesen pengecasan EV awam yang mencukupi dipasang di lokasi strategik.",
    descriptionEn: "Sufficient public EV charging stations installed at strategic urban hotspots.",
  },
  {
    id: "mob-smart-parking",
    category: "Smart Mobility",
    nameMs: "Peta & Pembayaran Letak Kereta Pintar",
    nameEn: "Smart Parking Guidance & Payment",
    descriptionMs: "Sistem parkir menggunakan sensor pintar yang dihubungkan dengan aplikasi penunjuk slot kosong.",
    descriptionEn: "Parking system using smart sensors connected to an app indicating vacant slots.",
  },
  {
    id: "mob-micromobility",
    category: "Smart Mobility",
    nameMs: "Laluan & Kenderaan Mikromobiliti Bersepadu",
    nameEn: "Integrated Micromobility & Bike Lanes",
    descriptionMs: "Zon mesra pejalan kaki dengan sewaan skuter elektrik dan basikal berbumbung.",
    descriptionEn: "Pedestrian-friendly zones with electric scooter rentals and covered bike lanes.",
  },

  // Smart Environment
  {
    id: "env-air-quality",
    category: "Smart Environment",
    nameMs: "Sensor Pemantauan Kualiti Udara (AQI)",
    nameEn: "Air Quality Index (AQI) Sensor Network",
    descriptionMs: "Rangkaian stesen pemantauan kualiti udara setempat dengan paparan data masa nyata kepada umum.",
    descriptionEn: "Hyperlocal air quality monitoring network with real-time public data displays.",
  },
  {
    id: "env-flood-warning",
    category: "Smart Environment",
    nameMs: "Sistem Amaran Awal Banjir Automatik",
    nameEn: "Automated Flash Flood Early Warning System",
    descriptionMs: "Penderia paras air sungai dan longkang utama bersepadu dengan siren dan SMS amaran automatik.",
    descriptionEn: "River and main drain water level sensors integrated with sirens and automated SMS warnings.",
  },
  {
    id: "env-smart-lighting",
    category: "Smart Environment",
    nameMs: "Lampu Jalan Pintar (LED IoT)",
    nameEn: "Smart LED IoT Streetlighting",
    descriptionMs: "Lebih daripada 80% lampu jalan ditukar ke LED yang mempunyai penderiaan kerosakan automatik.",
    descriptionEn: "Over 80% of streetlighting converted to smart dimmer LEDs with automated fault reporting.",
  },
  {
    id: "env-waste-monitoring",
    category: "Smart Environment",
    nameMs: "Pengurusan Sisa Pepejal Beraras Sensor",
    nameEn: "Sensor-Based Smart Waste Management",
    descriptionMs: "Tong sampah pintar komersial yang menghantar isyarat apabila penuh bagi pengoptimuman laluan lori.",
    descriptionEn: "Commercial bins transmitting fullness signals to optimize waste truck collection routes.",
  },
  {
    id: "env-green-buildings",
    category: "Smart Environment",
    nameMs: "Insentif Bangunan Hijau GBI",
    nameEn: "Green Building Index (GBI) Rating Support",
    descriptionMs: "Polisi bandar raya menyokong dan memberi kelonggaran cukai bagi pemaju bangunan berstatus GBI.",
    descriptionEn: "City policies supporting and providing tax rebates to developers of GBI-certified buildings.",
  },

  // Smart Economy
  {
    id: "eco-cashless",
    category: "Smart Economy",
    nameMs: "Saranan Bandar Tanpa Tunai",
    nameEn: "Cashless City Adoption Rate",
    descriptionMs: "Lebih 90% peniaga pasar, gerai dan kedai runcit menerima bayaran e-dompet (DuitNow).",
    descriptionEn: "Over 90% of local markets, hawkers, and retail accepting e-wallet (DuitNow) payments.",
  },
  {
    id: "eco-startups",
    category: "Smart Economy",
    nameMs: "Inkubator Startup & Hab Inovasi",
    nameEn: "Startup Incubators & Innovation Hubs",
    descriptionMs: "Penyediaan pusat pemikiran reka bentuk, fasiliti ko-working tajaan majlis untuk usahawan teknologi.",
    descriptionEn: "Provision of design thinking centers and co-working spaces sponsored by council for tech startups.",
  },
  {
    id: "eco-5g-coverage",
    category: "Smart Economy",
    nameMs: "Liputan Rangkaian Jalur Lebar 5G",
    nameEn: "5G Telecommunications Coverage",
    descriptionMs: "Liputan rangkaian mudah alih berkelajuan ultra-tinggi menepati standard liputan 95% kawasan berpenduduk.",
    descriptionEn: "Ultra-high-speed mobile network coverage covering over 95% of populated zones.",
  },
  {
    id: "eco-smart-tourism",
    category: "Smart Economy",
    nameMs: "Sistem Pelancongan Pintar",
    nameEn: "Smart Tourism Digital Services",
    descriptionMs: "Promosi digital interaktif dengan kod QR, panduan audio GPS, dan realiti terimbuh (AR) di mercu tanda.",
    descriptionEn: "Interactive digital promotion with QR codes, GPS audio tours, and AR guides at historical spots.",
  },
  {
    id: "eco-industrial-iot",
    category: "Smart Economy",
    nameMs: "Automasi Rantaian Bekalan & IoT Industri",
    nameEn: "Industrial IoT & Supply Chain Automation",
    descriptionMs: "Zon perindustrian bandar yang mengamalkan integrasi sensor IoT bagi pemantauan pelepasan asap dan logistik.",
    descriptionEn: "Industrial zones adopting IoT sensor integrations to monitor factory emissions and logistics.",
  },

  // Smart Living
  {
    id: "liv-cctv-analytics",
    category: "Smart Living",
    nameMs: "Rangkaian CCTV Keselamatan Komuniti Ber-AI",
    nameEn: "AI Safety CCTV Community Network",
    descriptionMs: "Kamera pemantauan bandar dihubungkan dengan AI pengecaman plat nombor serta pengesan kejadian pelik.",
    descriptionEn: "City surveillance cameras powered by AI for vehicle plate reading and anomaly detection.",
  },
  {
    id: "liv-telemedicine",
    category: "Smart Living",
    nameMs: "Sistem Telekesihatan & Klinik Komuniti Pintar",
    nameEn: "Smart Telehealth & Responsive Clinics",
    descriptionMs: "Ketersediaan konsultasi doktor online dan pusat pemeriksaan kesihatan pintar di kawasan PPR.",
    descriptionEn: "Availability of online doctor consultations and smart health screening kiosks in public housing areas.",
  },
  {
    id: "liv-emergency-kiosks",
    category: "Smart Living",
    nameMs: "Butang & Tiang Bantuan Kecemasan",
    nameEn: "Emergency Assistance Integrated Kiosks",
    descriptionMs: "Tiang bantuan interaktif kecemasan dengan interkom terus ke pusat kawalan pihak berkuasa.",
    descriptionEn: "Interactive physical emergency pillars with direct voice link to police & rescue centers.",
  },
  {
    id: "liv-smart-parks",
    category: "Smart Living",
    nameMs: "Taman Rekreasi Pintar Ber-IoT",
    nameEn: "IoT-Enabled Interactive Public Parks",
    descriptionMs: "Taman awam dengan lampu solar pintar, pengesan kualiti tanah/air kolam, dan wifi komuniti.",
    descriptionEn: "Public parks featuring solar-smart lighting, soil & pond monitoring, and community Wi-Fi.",
  },
  {
    id: "liv-smart-disaster",
    category: "Smart Living",
    nameMs: "Sistem Sokongan Tindak Balas Bencana Pintar",
    nameEn: "Smart Disaster Response Support System",
    descriptionMs: "Peta risiko digital masa nyata yang mengkoordinasikan pasukan bomba, polis dan sivil semasa bencana.",
    descriptionEn: "Real-time digital hazard mapping that coordinates civil rescue authorities during emergencies.",
  },

  // Smart People
  {
    id: "peo-digital-literacy",
    category: "Smart People",
    nameMs: "Program Literasi & Kompetensi Digital Awam",
    nameEn: "Public Digital Literacy & Upskilling Programs",
    descriptionMs: "Bengkel percuma tentang pengaturcaraan, kecerdasan buatan, dan keselamatan siber untuk komuniti.",
    descriptionEn: "Franchised free monthly coding, AI courses, and cyber security workshops for community clusters.",
  },
  {
    id: "peo-smart-schools",
    category: "Smart People",
    nameMs: "Peralatan Kelas Pintar & Bilik STEM",
    nameEn: "Smart Classrooms & STEM Resources",
    descriptionMs: "Sekolah harian kebangsaan dibekalkan kelengkapan komputer munasabah dan peralatan makmal robotics.",
    descriptionEn: "Local national schools fully equipped with stable computing benches and robotics lab kits.",
  },
  {
    id: "peo-social-portal",
    category: "Smart People",
    nameMs: "Portal Sukarelawan & Kebajikan Komuniti",
    nameEn: "Volunteer & Community Mutual Aid App",
    descriptionMs: "Aplikasi yang memadankan keperluan kebajikan keluarga miskin dengan sukarelawan berdekatan.",
    descriptionEn: "Application matching basic social support of lower income brackets with neighborhood volunteers.",
  },
  {
    id: "peo-digital-inclusion",
    category: "Smart People",
    nameMs: "Pusat Digital Komuniti (PDK) PPR",
    nameEn: "PPR Community Digital Inclusion Centers",
    descriptionMs: "Pusat khas di perumahan berpendapatan rendah yang menyediakan akses komputer dan internet percuma.",
    descriptionEn: "Subsidized centers inside low-cost apartments providing computing labs and free training.",
  },
  {
    id: "peo-e-participation",
    category: "Smart People",
    nameMs: "Undian & Pengundian Tempatan Maya",
    nameEn: "Virtual Citizen Townhall & Local Polling",
    descriptionMs: "Saluran digital maklum balas terus untuk warga kota memilih keutamaan pembangunan tempatan.",
    descriptionEn: "Direct digital consultation allowing city dwellers to vote or poll local development priorities.",
  },
];

export const INITIAL_CITIES: CityData[] = [
  {
    id: "kuala-lumpur",
    name: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    population: "1.98 Juta",
    totalIndicators: 30,
    scores: {
      "Smart Governance": 85,
      "Smart Mobility": 70,
      "Smart Environment": 80,
      "Smart Economy": 75,
      "Smart Living": 82,
      "Smart People": 76,
    },
    indicatorValues: {
      "gov-online-services": true,
      "gov-open-data": true,
      "gov-e-payment": true,
      "gov-wifi": true,
      "gov-citizen-engagement": false, // missing (hence 85%)
      
      "mob-traffic-mgmt": true,
      "mob-realtime-transit": true,
      "mob-ev-infra": false,
      "mob-smart-parking": true,
      "mob-micromobility": false, // missing (hence 70%)

      "env-air-quality": true,
      "env-flood-warning": true,
      "env-smart-lighting": true,
      "env-waste-monitoring": true,
      "env-green-buildings": false, // missing (hence 80%)

      "eco-cashless": true,
      "eco-startups": true,
      "eco-5g-coverage": true,
      "eco-smart-tourism": false,
      "eco-industrial-iot": false, // missing (hence 75% after adjustments)

      "liv-cctv-analytics": true,
      "liv-telemedicine": true,
      "liv-emergency-kiosks": false,
      "liv-smart-parks": true,
      "liv-smart-disaster": true,

      "peo-digital-literacy": true,
      "peo-smart-schools": true,
      "peo-social-portal": false,
      "peo-digital-inclusion": true,
      "peo-e-participation": false,
    },
    projects: [
      {
        id: "proj-kl-itms",
        name: "Sistem Lampu Isyarat Pintar AI Bukit Bintang",
        category: "Smart Mobility",
        budget: 15400000,
        status: "Ongoing",
        descriptionMs: "Pemasangan kamera AI penderia kesesakan serta pelarasan isyarat hijau lampu trafik masa nyata.",
        descriptionEn: "Deploying AI camera-based congestion sensors to adjust Bukit Bintang traffic lights dynamically.",
        targetImpact: "Mengubah masa menunggu persimpangan sebanyak 22% semasa waktu puncak.",
        timeline: "Jan 2026 - Dis 2026",
      },
      {
        id: "proj-kl-portal",
        name: "Portal Data Terbuka DBKL (DBKL Open Data v2)",
        category: "Smart Governance",
        budget: 1200000,
        status: "Completed",
        descriptionMs: "Menaik taraf portal sedia ada bagi menyokong API langsung geospatial dan rekod demografi masa nyata.",
        descriptionEn: "Upgrading existing open data portal to support direct geospatial APIs and real-time demographic assets.",
        targetImpact: "Penyediaan 180+ dataset terbuka baharu untuk akses pembangun swasta & akademik.",
        timeline: "Jul 2025 - Mac 2026",
      },
      {
        id: "proj-kl-flood",
        name: "Sensor Paras Air Sungai & Siren Amaran Awal Gombak-Klang",
        category: "Smart Environment",
        budget: 6800000,
        status: "Completed",
        descriptionMs: "Penyepaduan 42 sensor paras air sungai utama dengan amaran SMS terus bagi penduduk risiko kilat.",
        descriptionEn: "Integrating 42 river level telemetry nodes with direct SMS notification hooks for low-lying regions.",
        targetImpact: "Amaran banjir kilat 15-20 minit lebih pantas di kawasan hotspot Sentul dan Jalan Ampang.",
        timeline: "Sep 2025 - Mei 2026",
      },
      {
        id: "proj-kl-cc",
        name: "Kompleks Pemantauan CCTV AI Bersepadu DBKL",
        category: "Smart Living",
        budget: 28000000,
        status: "Ongoing",
        descriptionMs: "Pusat kawalan keselamatan bersepadu menghubungkan 2,000 CCTV pintar dengan algoritma pengecaman.",
        descriptionEn: "Unified operations safety command linking 2,000 smart CCTV cameras with multi-analytics.",
        targetImpact: "Meningkatkan tindak balas kecemasan keselamatan dari 12 minit ke 7 minit di tengah KL.",
        timeline: "Dis 2025 - Ogo 2026",
      }
    ],
    history: [
      { date: "Ogos 2025", score: 71 },
      { date: "Nov 2025", score: 74 },
      { date: "Feb 2026", score: 76 },
      { date: "Jun 2026", score: 78 },
    ],
  },
  {
    id: "putrajaya",
    name: "Putrajaya",
    state: "Wilayah Persekutuan",
    population: "120,000",
    totalIndicators: 30,
    scores: {
      "Smart Governance": 95,
      "Smart Mobility": 80,
      "Smart Environment": 90,
      "Smart Economy": 85,
      "Smart Living": 90,
      "Smart People": 85,
    },
    indicatorValues: {
      "gov-online-services": true,
      "gov-open-data": true,
      "gov-e-payment": true,
      "gov-wifi": true,
      "gov-citizen-engagement": true,
      
      "mob-traffic-mgmt": true,
      "mob-realtime-transit": true,
      "mob-ev-infra": true,
      "mob-smart-parking": true,
      "mob-micromobility": false,

      "env-air-quality": true,
      "env-flood-warning": true,
      "env-smart-lighting": true,
      "env-waste-monitoring": true,
      "env-green-buildings": true,

      "eco-cashless": true,
      "eco-startups": true,
      "eco-5g-coverage": true,
      "eco-smart-tourism": true,
      "eco-industrial-iot": false,

      "liv-cctv-analytics": true,
      "liv-telemedicine": true,
      "liv-emergency-kiosks": true,
      "liv-smart-parks": true,
      "liv-smart-disaster": true,

      "peo-digital-literacy": true,
      "peo-smart-schools": true,
      "peo-social-portal": true,
      "peo-digital-inclusion": true,
      "peo-e-participation": false,
    },
    projects: [
      {
        id: "proj-pj-solar",
        name: "Projek Panel Solar Atap Kompleks Jabatan Persekutuan",
        category: "Smart Environment",
        budget: 18500000,
        status: "Ongoing",
        descriptionMs: "Pemasangan kuasa solar fotovoltaik (PV) di 15 bumbung kompleks kementerian Putrajaya.",
        descriptionEn: "Installing rooftop solar PV panels on 15 federal ministry buildings in Putrajaya.",
        targetImpact: "Menjana penjimatan bil utiliti RM 3.5 juta setahun dan pengurangan 8,000 tan karbon.",
        timeline: "Feb 2026 - Nov 2027",
      },
      {
        id: "proj-pj-bus",
        name: "Sistem Kenderaan Autonomi Penumpang Pintar (ART)",
        category: "Smart Mobility",
        budget: 32000000,
        status: "Completed",
        descriptionMs: "Laluan khas pemanduan autonomi tanpa pemandu bagi laluan Boulevard Putrajaya.",
        descriptionEn: "Deploying driverless autonomous trackless tram (ART) routes along the Putrajaya Boulevard.",
        targetImpact: "Kapasiti 300 penumpang setiap perjalanan, menghubungkan Presint 1-4 secara mesra karbon.",
        timeline: "Jun 2025 - Mac 2026",
      }
    ],
    history: [
      { date: "Ogos 2025", score: 82 },
      { date: "Nov 2025", score: 85 },
      { date: "Feb 2026", score: 87 },
      { date: "Jun 2026", score: 88 },
    ],
  },
  {
    id: "georgetown",
    name: "Georgetown",
    state: "Pulau Pinang",
    population: "700,000",
    totalIndicators: 30,
    scores: {
      "Smart Governance": 75,
      "Smart Mobility": 65,
      "Smart Environment": 85,
      "Smart Economy": 80,
      "Smart Living": 78,
      "Smart People": 72,
    },
    indicatorValues: {
      "gov-online-services": true,
      "gov-open-data": false,
      "gov-e-payment": true,
      "gov-wifi": true,
      "gov-citizen-engagement": false,
      
      "mob-traffic-mgmt": true,
      "mob-realtime-transit": false,
      "mob-ev-infra": false,
      "mob-smart-parking": true,
      "mob-micromobility": true,

      "env-air-quality": true,
      "env-flood-warning": true,
      "env-smart-lighting": true,
      "env-waste-monitoring": true,
      "env-green-buildings": true,

      "eco-cashless": true,
      "eco-startups": true,
      "eco-5g-coverage": true,
      "eco-smart-tourism": true,
      "eco-industrial-iot": false,

      "liv-cctv-analytics": true,
      "liv-telemedicine": false,
      "liv-emergency-kiosks": false,
      "liv-smart-parks": true,
      "liv-smart-disaster": true,

      "peo-digital-literacy": true,
      "peo-smart-schools": true,
      "peo-social-portal": false,
      "peo-digital-inclusion": true,
      "peo-e-participation": false,
    },
    projects: [
      {
        id: "proj-pg-park",
        name: "Penang Smart Parking (PSP) Expansion",
        category: "Smart Mobility",
        budget: 5800000,
        status: "Completed",
        descriptionMs: "Peluasan sensor bawah tanah di lorong-lorong warisan Georgetown warisan dunia UNESCO.",
        descriptionEn: "Expansion of smart in-ground parking sensors inside sensitive UNESCO world heritage zones.",
        targetImpact: "Kurangkan kesesakan mencari parkir sebanyak 35% di zon tumpuan pelancong.",
        timeline: "Feb 2025 - Jan 2026",
      },
      {
        id: "proj-pg-waste",
        name: "Sensor Tong Sampah Pintar Kawasan Awam Georgerown",
        category: "Smart Environment",
        budget: 1800000,
        status: "Ongoing",
        descriptionMs: "Memasang penderia penuh bagi 450 tong sampah besar sekitar bandar Georgetown untuk laluan kutipan bijak.",
        descriptionEn: "Installing fill-level sensors to 450 commercial public bins for scheduling optimization.",
        targetImpact: "Penjimatan kos bahan api lori kutipan MPSPC sebanyak 15% setahun.",
        timeline: "Mac 2026 - Dis 2026",
      }
    ],
    history: [
      { date: "Ogos 2025", score: 72 },
      { date: "Nov 2025", score: 74 },
      { date: "Feb 2026", score: 75 },
      { date: "Jun 2026", score: 76 },
    ],
  },
  {
    id: "johor-bahru",
    name: "Johor Bahru",
    state: "Johor",
    population: "850,000",
    totalIndicators: 30,
    scores: {
      "Smart Governance": 68,
      "Smart Mobility": 70,
      "Smart Environment": 65,
      "Smart Economy": 78,
      "Smart Living": 72,
      "Smart People": 74,
    },
    indicatorValues: {
      "gov-online-services": true,
      "gov-open-data": false,
      "gov-e-payment": true,
      "gov-wifi": false,
      "gov-citizen-engagement": false,
      
      "mob-traffic-mgmt": true,
      "mob-realtime-transit": true,
      "mob-ev-infra": true,
      "mob-smart-parking": false,
      "mob-micromobility": false,

      "env-air-quality": true,
      "env-flood-warning": false,
      "env-smart-lighting": true,
      "env-waste-monitoring": false,
      "env-green-buildings": true,

      "eco-cashless": true,
      "eco-startups": true,
      "eco-5g-coverage": true,
      "eco-smart-tourism": false,
      "eco-industrial-iot": true,

      "liv-cctv-analytics": true,
      "liv-telemedicine": true,
      "liv-emergency-kiosks": false,
      "liv-smart-parks": false,
      "liv-smart-disaster": true,

      "peo-digital-literacy": true,
      "peo-smart-schools": false,
      "peo-social-portal": true,
      "peo-digital-inclusion": true,
      "peo-e-participation": false,
    },
    projects: [
      {
        id: "proj-jb-cc",
        name: "JB Smart City Command Centre (MBJB Command Portal)",
        category: "Smart Governance",
        budget: 14500000,
        status: "Ongoing",
        descriptionMs: "Pembangunan sistem pengurusan maklumat bencana dan operasi bandaraya Johor Bahru setempat.",
        descriptionEn: "Development of localized disaster alert and municipal operations monitoring portal in Johor Bahru.",
        targetImpact: "Penyepaduan 5 agensi penyelamat utama dalam satu skrin operasi.",
        timeline: "Nov 2025 - Nov 2026",
      }
    ],
    history: [
      { date: "Ogos 2025", score: 65 },
      { date: "Nov 2025", score: 68 },
      { date: "Feb 2026", score: 70 },
      { date: "Jun 2026", score: 71 },
    ],
  },
];
